# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import interweave_pb2 as interweave__pb2

GRPC_GENERATED_VERSION = '1.68.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in interweave_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class InterweaveServiceStub(object):
    """=============================================================================
    Service Definition
    =============================================================================

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Forward = channel.unary_unary(
                '/interweave.InterweaveService/Forward',
                request_serializer=interweave__pb2.ForwardRequest.SerializeToString,
                response_deserializer=interweave__pb2.ForwardResponse.FromString,
                _registered_method=True)
        self.StreamForward = channel.unary_stream(
                '/interweave.InterweaveService/StreamForward',
                request_serializer=interweave__pb2.ForwardRequest.SerializeToString,
                response_deserializer=interweave__pb2.StreamForwardResponse.FromString,
                _registered_method=True)
        self.Generate = channel.unary_unary(
                '/interweave.InterweaveService/Generate',
                request_serializer=interweave__pb2.GenerateRequest.SerializeToString,
                response_deserializer=interweave__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.StreamGenerate = channel.unary_stream(
                '/interweave.InterweaveService/StreamGenerate',
                request_serializer=interweave__pb2.GenerateRequest.SerializeToString,
                response_deserializer=interweave__pb2.GenerateResponse.FromString,
                _registered_method=True)
        self.QueryRoute = channel.unary_unary(
                '/interweave.InterweaveService/QueryRoute',
                request_serializer=interweave__pb2.RouteQueryRequest.SerializeToString,
                response_deserializer=interweave__pb2.RouteQueryResponse.FromString,
                _registered_method=True)
        self.RegisterNode = channel.unary_unary(
                '/interweave.InterweaveService/RegisterNode',
                request_serializer=interweave__pb2.RegisterNodeRequest.SerializeToString,
                response_deserializer=interweave__pb2.RegisterNodeResponse.FromString,
                _registered_method=True)
        self.GetTopology = channel.unary_unary(
                '/interweave.InterweaveService/GetTopology',
                request_serializer=interweave__pb2.GetTopologyRequest.SerializeToString,
                response_deserializer=interweave__pb2.GetTopologyResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/interweave.InterweaveService/HealthCheck',
                request_serializer=interweave__pb2.InterweaveHealthRequest.SerializeToString,
                response_deserializer=interweave__pb2.InterweaveHealthResponse.FromString,
                _registered_method=True)


class InterweaveServiceServicer(object):
    """=============================================================================
    Service Definition
    =============================================================================

    """

    def Forward(self, request, context):
        """Core forward pass (tensor-level)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamForward(self, request, context):
        """Streaming forward pass
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Generate(self, request, context):
        """High-level generation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamGenerate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryRoute(self, request, context):
        """Routing and discovery
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RegisterNode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTopology(self, request, context):
        """Topology
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_InterweaveServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Forward': grpc.unary_unary_rpc_method_handler(
                    servicer.Forward,
                    request_deserializer=interweave__pb2.ForwardRequest.FromString,
                    response_serializer=interweave__pb2.ForwardResponse.SerializeToString,
            ),
            'StreamForward': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamForward,
                    request_deserializer=interweave__pb2.ForwardRequest.FromString,
                    response_serializer=interweave__pb2.StreamForwardResponse.SerializeToString,
            ),
            'Generate': grpc.unary_unary_rpc_method_handler(
                    servicer.Generate,
                    request_deserializer=interweave__pb2.GenerateRequest.FromString,
                    response_serializer=interweave__pb2.GenerateResponse.SerializeToString,
            ),
            'StreamGenerate': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamGenerate,
                    request_deserializer=interweave__pb2.GenerateRequest.FromString,
                    response_serializer=interweave__pb2.GenerateResponse.SerializeToString,
            ),
            'QueryRoute': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryRoute,
                    request_deserializer=interweave__pb2.RouteQueryRequest.FromString,
                    response_serializer=interweave__pb2.RouteQueryResponse.SerializeToString,
            ),
            'RegisterNode': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterNode,
                    request_deserializer=interweave__pb2.RegisterNodeRequest.FromString,
                    response_serializer=interweave__pb2.RegisterNodeResponse.SerializeToString,
            ),
            'GetTopology': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTopology,
                    request_deserializer=interweave__pb2.GetTopologyRequest.FromString,
                    response_serializer=interweave__pb2.GetTopologyResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=interweave__pb2.InterweaveHealthRequest.FromString,
                    response_serializer=interweave__pb2.InterweaveHealthResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'interweave.InterweaveService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('interweave.InterweaveService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class InterweaveService(object):
    """=============================================================================
    Service Definition
    =============================================================================

    """

    @staticmethod
    def Forward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interweave.InterweaveService/Forward',
            interweave__pb2.ForwardRequest.SerializeToString,
            interweave__pb2.ForwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamForward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/interweave.InterweaveService/StreamForward',
            interweave__pb2.ForwardRequest.SerializeToString,
            interweave__pb2.StreamForwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Generate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interweave.InterweaveService/Generate',
            interweave__pb2.GenerateRequest.SerializeToString,
            interweave__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamGenerate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/interweave.InterweaveService/StreamGenerate',
            interweave__pb2.GenerateRequest.SerializeToString,
            interweave__pb2.GenerateResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryRoute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interweave.InterweaveService/QueryRoute',
            interweave__pb2.RouteQueryRequest.SerializeToString,
            interweave__pb2.RouteQueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RegisterNode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interweave.InterweaveService/RegisterNode',
            interweave__pb2.RegisterNodeRequest.SerializeToString,
            interweave__pb2.RegisterNodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTopology(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interweave.InterweaveService/GetTopology',
            interweave__pb2.GetTopologyRequest.SerializeToString,
            interweave__pb2.GetTopologyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/interweave.InterweaveService/HealthCheck',
            interweave__pb2.InterweaveHealthRequest.SerializeToString,
            interweave__pb2.InterweaveHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
